atsign-foundation/atmosphere_pro

lib/desktop_screens/desktop_common_widgets/desktop_switch_atsign.dart
lib/desktop_screens/desktop_welcome_screen/desktop_welcome_screen.dart
lib/view_models/welcome_screen_view_model.dart

-> updated switch atsign modal with menu items. 

switch atsign modal implementation updated with menu items

---

lib/desktop_screens/desktop_common_widgets/desktop_switch_atsign.dart
lib/desktop_screens/desktop_welcome_screen/desktop_welcome_screen.dart
lib/screens/common_widgets/side_bar.dart
lib/services/backend_service.dart
lib/services/common_functions.dart
lib/utils/text_strings.dart
pubspec.yaml

-> Added option to backup and delete atsign

delete atsign and backup atKey 

---

lib/app.dart
lib/screens/common_widgets/app_bar.dart
lib/screens/common_widgets/side_bar.dart
lib/screens/welcome_screen/welcome_screen.dart
lib/services/backend_service.dart
lib/view_models/file_download_checker.dart
lib/view_models/history_provider.dart

Contains fix for [Atmosphere Pro - Add in app visual cue for received files](https://github.com/atsign-foundation/apps/issues/290)

Added file_download_checker for visual cue

---

lib/screens/common_widgets/custom_heading.dart
lib/screens/common_widgets/side_bar.dart
lib/screens/common_widgets/side_bar_list_item.dart
lib/screens/welcome_screen/widgets/welcome_sceen_home.dart
lib/view_models/history_provider.dart
pubspec.yaml

- resolved small tablet ui issue [#496](https://github.com/atsign-foundation/apps/issues/496)

Feat/smaller tablet UI

---

LICENSE
lib/screens/common_widgets/confirmation_dialog.dart
lib/screens/common_widgets/side_bar.dart
lib/screens/history/widgets/edit_bottomsheet.dart
lib/screens/history/widgets/sent_file_list_tile.dart
lib/screens/welcome_screen/widgets/welcome_sceen_home.dart
lib/utils/text_strings.dart
lib/utils/text_styles.dart
lib/view_models/history_provider.dart
pubspec.yaml

- added delete option for sent files
- moved switch atsign function to welcome screen.

sent file delete option added and switch atsign added in welcome screen

---

lib/desktop_screens/desktop_history/widgets/desktop_received_file_details.dart
lib/desktop_screens/desktop_home/desktop_home.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_file_card.dart
lib/services/backend_service.dart
lib/utils/constants.dart
lib/view_models/file_download_checker.dart
lib/view_models/history_provider.dart

Contains https://github.com/atsign-foundation/apps/issues/460#issuecomment-1035099860

Added individual download directory

---

lib/services/common_utility_functions.dart

- added confirmation dialog box before removing atsigns from device for [491](https://github.com/atsign-foundation/apps/issues/491)

confirmation dialog added before removing atsign

---

lib/screens/my_files/widgets/photos.dart
lib/screens/my_files/widgets/recents.dart

Contains a probable fix for [App keeps crashing when looking at My Files](https://github.com/atsign-foundation/apps/issues/525) .

Replaced wrap with gridview

---

android/app/src/main/AndroidManifest.xml
lib/screens/common_widgets/custom_button.dart

Resolved issue of showing up blank button on splash screen.

Resolved - Showing up blank button on splash screen 

---

lib/desktop_screens/desktop_common_widgets/dektop_custom_person_tile.dart
lib/desktop_screens/desktop_common_widgets/desktop_person_horizontal_tile.dart
lib/desktop_screens/desktop_common_widgets/desktop_person_vertical_tile.dart
lib/desktop_screens/desktop_common_widgets/person_vertical_tile.dart
lib/desktop_screens/desktop_history/widgets/desktop_received_file_list_tile.dart
lib/desktop_screens/desktop_history/widgets/desktop_sent_file_list_tile.dart
lib/screens/common_widgets/custom_circle_avatar.dart
lib/screens/common_widgets/person_vertical_tile.dart
lib/screens/common_widgets/side_bar.dart
lib/screens/history/history_screen.dart
lib/screens/history/widgets/received_file_list_tile.dart
lib/screens/my_files/widgets/photos.dart
lib/screens/my_files/widgets/recents.dart
lib/screens/my_files/widgets/videos.dart
lib/services/common_utility_functions.dart

-> added errorBuilder where the image is displaying
-> utilized errorBuilder method in File

image render exception handled

---

lib/data_models/version.dart
lib/screens/welcome_screen/welcome_screen.dart
lib/services/backend_service.dart
lib/services/version_service.dart

- added version upgrader for desktop and mobile platforms [557](https://github.com/atsign-foundation/apps/issues/557)

version service updated

---

lib/desktop_screens/desktop_common_widgets/desktop_selected_files.dart
lib/desktop_screens/desktop_download_all_files/desktop_download_all_file.dart
lib/desktop_screens/desktop_history/desktop_history.dart
lib/desktop_screens/desktop_history/widgets/desktop_received_file_details.dart
lib/desktop_screens/desktop_history/widgets/desktop_sent_file_details.dart
lib/desktop_screens/desktop_history/widgets/desktop_transfer_overlapping.dart
lib/desktop_screens/desktop_home/desktop_home.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_apk.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_audios.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_documents.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_photos.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_recent.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_unknowns.dart
lib/desktop_screens/desktop_my_files/widgets/desktop_videos.dart
lib/desktop_screens/desktop_welcome_screen/desktop_welcome_screen.dart
lib/desktop_screens/trusted_sender/desktop_trusted_sender.dart
lib/screens/common_widgets/confirmation_dialog.dart
lib/screens/history/widgets/file_recipients.dart
lib/screens/history/widgets/received_file_list_tile.dart
lib/screens/my_files/widgets/recents.dart
lib/screens/my_files/widgets/videos.dart
lib/screens/welcome_screen/widgets/welcome_screen_received_files.dart
lib/services/at_error_dialog.dart
lib/services/backend_service.dart
lib/services/common_utility_functions.dart
lib/services/version_service.dart
lib/utils/text_strings.dart

Completed updating app wording text string files.

Wording Updates

---

lib/data_models/version.dart
lib/services/version_service.dart
lib/utils/constants.dart
lib/utils/text_strings.dart

-> Added version upgrader using release tag

feat:557 - release tag used to identify version upgrade

---

lib/services/notification_service.dart
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake
windows/local_notifier_plugin.cpp
windows/wintoastlib.cpp
windows/wintoastlib.h

-> fixed issue for notifications on windows
-> added al alternate package for local_notification

windows notification added and exception resolved

---

lib/desktop_screens/desktop_history/widgets/desktop_transfer_overlapping.dart
lib/services/version_service.dart

- removed build number comparison in version service.
- added key property in CustomPersonVerticalTile

build number comparision removed

---

lib/view_models/history_provider.dart

- optimized periodic refreshing of history screen data.

file transfer refresh optmized

---

lib/screens/common_widgets/custom_onboarding.dart
lib/services/backend_service.dart
lib/view_models/history_provider.dart

- resolved issue with received items disappers.
- changed the order of populating history data.

received items disappear issue resolved

---

lib/services/backend_service.dart
lib/view_models/history_provider.dart

- only fetching changed ids in received files refresh.

optmized periodic refresh for received files

---

lib/screens/common_widgets/custom_onboarding.dart

Added error callback on Onboarding failure.

Added snackbar on error callback of onboarding

---

lib/screens/common_widgets/custom_onboarding.dart
lib/services/backend_service.dart
lib/view_models/history_provider.dart
pubspec.yaml

Contains code to `download trusted contact's files on app start`.

Added code to download trusted contacts files on app start

---

lib/screens/common_widgets/side_bar_list_item.dart

Updated font size for side bar title.

Fixed sidebar font overlap issue

---

lib/desktop_screens/desktop_history/widgets/desktop_received_file_details.dart
lib/desktop_screens/desktop_history/widgets/desktop_received_file_list_tile.dart

**- What I did - fixed the formatting on file details (time, no of files)**
**- How I did it - removed the extra space from time format and replaced files with File(s)**
Ticket link - https://github.com/atsign-foundation/apps/issues/603

fixed formatting on file details [#603]

---

lib/screens/common_widgets/add_contact.dart
lib/utils/text_strings.dart

**- What I did - fixed the wordings in mobile and desktop.**
ticket link - https://github.com/atsign-foundation/apps/issues/431

fixed the wordings in mobile and desktop

---

lib/screens/trusted_contacts/trusted_contacts.dart

**- What I did - removed the gridview and switch* from trusted senders list.*
ticket link - https://github.com/atsign-foundation/apps/issues/611

removed the gridview and the toggle switch from trusted senders

---

lib/services/overlay_service.dart
lib/utils/text_strings.dart

Solved Issue #527 
https://github.com/atsign-foundation/apps/issues/527#event-6707726116

handled when files are failed to send to atsign

---

ios/Podfile.lock
lib/screens/common_widgets/add_contact.dart

**- What I did* - fixed the overflow on add contact screen*
ticket link - https://github.com/atsign-foundation/apps/issues/633

fixed the overflow on add contact screen

---

lib/services/overlay_service.dart

- improved ui of overlay in mobile.

overlay style updated

---

lib/desktop_screens/desktop_history/widgets/desktop_sent_file_details.dart
lib/desktop_screens/desktop_history/widgets/desktop_sent_file_list_tile.dart
lib/screens/history/widgets/sent_file_list_tile.dart
lib/utils/text_strings.dart

**- What I did - fixed the wordings in the received files section on desktop**
ticket link - https://github.com/atsign-foundation/apps/issues/603

fixed the wordings in the recieved files section on desktop

---

LICENSE
README.md
code_of_conduct.md

chore: new branding

---

lib/desktop_screens/desktop_common_widgets/dektop_custom_person_tile.dart
lib/desktop_screens/trusted_sender/desktop_empty_trusted_sender.dart
lib/desktop_screens/trusted_sender/desktop_trusted_sender.dart
lib/screens/common_widgets/app_bar.dart
lib/screens/common_widgets/website_webview.dart
lib/screens/trusted_contacts/trusted_contacts.dart
lib/services/backend_service.dart
lib/services/overlay_service.dart
lib/view_models/trusted_sender_view_model.dart
pubspec.yaml

- Added fix for buffer size limit issue [#640](https://github.com/atsign-foundation/apps/issues/640)
- removed image data from `AtContact` model before saving in trusted sender key.
- removed image entry from `AtContact` tags

Fix 640/trusted senders

---

CONTRIBUTING.md
code_of_conduct.md

chore: new atPlatform logo

---

lib/view_models/history_provider.dart

Update for task [#576](https://github.com/atsign-foundation/apps/issues/576)

feat: error handling desktop

---

ios/Runner/Info.plist
lib/screens/welcome_screen/widgets/select_contact_widget.dart
lib/services/common_utility_functions.dart
lib/utils/text_strings.dart

[#653](https://github.com/atsign-foundation/apps/issues/653)

feat: change @sign to atSign

---

lib/screens/common_widgets/custom_onboarding.dart
lib/screens/welcome_screen/widgets/welcome_sceen_home.dart
lib/services/backend_service.dart
lib/view_models/history_provider.dart
lib/view_models/trusted_sender_view_model.dart

issue:https://github.com/atsign-foundation/apps/issues/667

fix: AtClientManage and syncService are used from

---

lib/screens/common_widgets/switch_at_sign.dart

[#677](https://github.com/atsign-foundation/apps/issues/677)

fix: switch atsign

---

lib/services/common_utility_functions.dart
pubspec.yaml

created a new branch and raised a new PR inorder to avoid the last blunder

chore: change single instance of @sign

---

pubspec.lock
pubspec.yaml

Fix this issue [#683](https://github.com/atsign-foundation/apps/issues/683)
Update at_onboarding: https://github.com/atsign-foundation/at_widgets/commit/8d58d8cfdced4af45f3c08019bc94c03f8fbc800
Should run code in this branch and test

fix: swiching atsign issue

---

lib/screens/trusted_contacts/trusted_contacts.dart

Contains a fix for the red screen error https://github.com/atsign-foundation/apps/issues/657#issuecomment-1201966281

fix: Added null check for trusted contacts

---

lib/utils/text_strings.dart

issue: https://github.com/atsign-foundation/apps/issues/629

chore: change text in remove items dialog

---

lib/desktop_screens/desktop_history/desktop_history.dart
lib/screens/history/history_screen.dart

**- What I did -  added fix for uppercase group names, close button resets the search in atmosphere pro **
ticket link - https://github.com/atsign-foundation/apps/issues/514

fix: added fix for uppercase group names, close button resets the search 

---

lib/screens/common_widgets/switch_at_sign.dart
lib/screens/trusted_contacts/trusted_contacts.dart
lib/services/common_utility_functions.dart
lib/view_models/history_provider.dart

Issue: https://github.com/atsign-foundation/apps/issues/693

chore: removed most of the warnings appearing

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Share Extension/Info.plist
lib/services/backend_service.dart
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
macos/Runner/Configs/AppInfo.xcconfig
macos/Runner/Info.plist
pubspec.lock
pubspec.yaml

- released atmopsherePro ios and macos 1.0.8.47

release: release ios and macos 1.0.8.47

---

lib/desktop_screens/desktop_history/widgets/desktop_received_file_details.dart

**- What I did - formatting on received files in desktop that includes wordings and styles**
ticket link - https://github.com/atsign-foundation/apps/issues/603

fix: formatting on received files in desktop

---

lib/desktop_screens/desktop_common_widgets/desktop_selected_contacts.dart
lib/desktop_screens/desktop_welcome_screen/widgets/welcome_screen_home.dart
lib/utils/text_strings.dart

issue: https://github.com/atsign-foundation/apps/issues/705

fix: added texts to change according to numbers

---

lib/services/common_utility_functions.dart

**- What I did - fixed the scroll not happening in delete atsign dialog box**
ticket link - https://github.com/atsign-foundation/apps/issues/704

fix: scroll in delete atsign dialog

---

ios/Podfile

- fix request camera permission

feat: fix request camera permission

---

lib/desktop_screens/desktop_history/widgets/desktop_received_file_details.dart

**- What I did - A formatting error on received files on desktop for downloading a file**

fix: downloading formatting in received files on desktop

---

lib/desktop_screens/desktop_history/widgets/desktop_received_file_list_tile.dart
lib/screens/common_widgets/add_contact.dart
lib/screens/history/widgets/received_file_list_tile.dart

issue: https://github.com/atsign-foundation/atmosphere_pro/issues/184

fix: contacts can now be added in desktop

---

android/app/src/main/AndroidManifest.xml

**- What I did - fixed the issue where receive_sharing_intent was not working. (Note - This fix is only for Android)**
ticket link - https://github.com/atsign-foundation/atmosphere_pro/issues/185

fix: sharing intent problem on android

---

lib/screens/common_widgets/add_contact.dart

Made width constant for adding contacts

chore: made width constant for adding contacts

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml

- release changes for atmopsherePro 1.0.9.50

build: release 1.0.9.50

---

lib/desktop_screens/desktop_history/widgets/desktop_received_file_list_tile.dart
lib/screens/common_widgets/confirmation_item_delete.dart
lib/screens/history/widgets/delete_bottomsheet.dart
lib/screens/history/widgets/received_file_list_tile.dart

issue: https://github.com/atsign-foundation/apps/issues/629
comment: https://github.com/atsign-foundation/apps/issues/629#issuecomment-1258422048

fix: files can be deleted from transfer history

---

ios/Podfile.lock
lib/screens/common_widgets/custom_onboarding.dart
lib/screens/history/transfer_history_screen.dart
lib/services/backend_service.dart
lib/services/common_utility_functions.dart
lib/view_models/file_transfer_provider.dart
lib/view_models/history_provider.dart
pubspec.lock

- Updating UI, when file is re-uploading
- Added auto-refresh for transfer history when file is received or sent.
- Showing infinite spinner when file is decrypting

Feat history monitor

---

lib/screens/common_widgets/app_bar_custom.dart
lib/screens/common_widgets/gradient_text_field_widget.dart
lib/screens/common_widgets/header_widget.dart
lib/screens/common_widgets/option_header_widget.dart
lib/screens/contact_new_version/add_contact_screen.dart
lib/screens/contact_new_version/blocked_contact_screen.dart
lib/screens/contact_new_version/contact_screen.dart
lib/screens/contact_new_version/group_contact_screen.dart
lib/screens/contact_new_version/trusted_contact_screen.dart
lib/screens/history/transfer_history_screen.dart
lib/screens/my_files/my_files_screen.dart
lib/screens/settings/settings_screen.dart
lib/screens/welcome_screen/welcome_screen.dart
lib/screens/welcome_screen/widgets/bottom_navigation_widget.dart

feat: fix UI on tablets

---

lib/screens/history/transfer_history_screen.dart
lib/screens/my_files/my_files_screen.dart
lib/view_models/history_provider.dart
lib/view_models/my_files_provider.dart

- showing individual entity in transfer history screen
- added preview for sent file item.

fix: showing individual entity for multiple atSign

---

lib/screens/common_widgets/linear_progress_bar.dart
lib/services/overlay_service.dart
pubspec.yaml

feat: change linear gradient progress

---

lib/screens/my_files/my_files_screen.dart
lib/screens/welcome_screen/widgets/welcome_sceen_home.dart

Fix count and select type file

fix: update and select files

---

lib/screens/common_widgets/website_webview.dart
pubspec.yaml

fix bug [#261](https://github.com/atsign-foundation/atmosphere_pro/issues/261)
increase of some packages and edit web_view screen

feat: fix error when updating latest onboarding flutter package

---

lib/routes/routes.dart
lib/screens/welcome_screen/welcome_screen.dart
lib/services/backend_service.dart

fix bug notification routes to the history screen

feat: fix bug notification routes to history screen

---

lib/desktop_screens/desktop_home/desktop_home.dart
lib/screens/common_widgets/custom_onboarding.dart
lib/services/backend_service.dart
macos/Podfile
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
pubspec.lock

- updated onboard error messages

fix: onboard error message updated

---

lib/services/file_transfer_service.dart
lib/utils/constants.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
pubspec.lock
pubspec.yaml

- dependency updated
- minor fixes in webview and encrypting service

chore: dependency update
